# coding: utf-8
#
# Copyright © Lyra Network.
# This file is part of Lyra Collect plugin for Odoo. See COPYING.md for license details.
#
# Author:    Lyra Network (https://www.lyra.com)
# Copyright: Copyright © Lyra Network
# License:   http://www.gnu.org/licenses/agpl.html GNU Affero General Public License (AGPL v3)

from odoo.tools.translate import _lt

# WARN: Do not modify code format here. This is managed by build files.
LYRA_PLUGIN_FEATURES = {
    'multi': True,
    'restrictmulti': False,
    'qualif': False,
    'shatwo': True,
}

LYRA_PARAMS = {
    'GATEWAY_CODE': 'Lyra',
    'GATEWAY_NAME': 'Lyra Collect',
    'BACKOFFICE_NAME': 'Lyra Expert',
    'SUPPORT_EMAIL': 'https://support.lyra.com/hc/fr/requests/new',
    'GATEWAY_URL': 'https://secure.lyra.com/vads-payment/',
    'SITE_ID': '12345678',
    'KEY_TEST': '1111111111111111',
    'KEY_PROD': '2222222222222222',
    'CTX_MODE': 'TEST',
    'SIGN_ALGO': 'SHA-256',
    'LANGUAGE': 'en',

    'GATEWAY_VERSION': 'V2',
    'PLUGIN_VERSION': '4.2.1',
    'CMS_IDENTIFIER': 'Odoo_17-18',
    'REST_URL': 'https://api.lyra.com/api-payment/',
    'STATIC_URL': 'https://static.lyra.com/static/'
}

LYRA_LANGUAGES = {
    'cn': _lt("Chinese"),
    'de': _lt("German"),
    'es': _lt("Spanish"),
    'en': _lt("English"),
    'fr': _lt("French"),
    'it': _lt("Italian"),
    'jp': _lt("Japanese"),
    'nl': _lt("Dutch"),
    'pl': _lt("Polish"),
    'pt': _lt("Portuguese"),
    'ru': _lt("Russian"),
    'sv': _lt("Swedish"),
    'tr': _lt("Turkish"),
}

LYRA_CARDS = {
    'CB': u'CB',
    'E-CARTEBLEUE': u'e-Carte Bleue',
    'MAESTRO': u'Maestro',
    'MASTERCARD': u'Mastercard',
    'VISA': u'Visa',
    'VISA_ELECTRON': u'Visa Electron',
    'VPAY': u'V PAY',
    'AMEX': u'American Express',
    'ACCORD_STORE': u'Cartes Enseignes Partenaires',
    'ACCORD_STORE_SB': u'Cartes Enseignes Partenaires (sandbox)',
    'AKULAKU_ID': u'Akulaku PayLater ID',
    'AKULAKU_PH': u'Akulaku PayLater PH',
    'ALINEA': u'Carte myalinea',
    'ALINEA_CDX': u'Carte Cadeau Alinéa',
    'ALINEA_CDX_SB': u'Carte Cadeau Alinéa (sandbox)',
    'ALINEA_SB': u'Carte myalinea (sandbox)',
    'ALIPAY': u'Alipay',
    'ALIPAY_CN': u'AlipayCN',
    'ALIPAY_HK': u'AlipayHK',
    'ALIPAY_PLUS': u'Alipay+',
    'ALLOBEBE_CDX': u'Carte Cadeau Allobébé',
    'ALLOBEBE_CDX_SB': u'Carte Cadeau Allobébé (sandbox)',
    'ALMA': u'Alma en 1 fois',
    'ALMA_10X': u'Alma en 10 fois',
    'ALMA_12X': u'Alma en 12 fois',
    'ALMA_2X': u'Alma en 2 fois',
    'ALMA_3X': u'Alma en 3 fois',
    'ALMA_4X': u'Alma en 4 fois',
    'APETIZ': u'Apetiz',
    'APPLE_PAY': u'Apple Pay',
    'AUCHAN': u'Carte Auchan',
    'AUCHAN_SB': u'Carte Auchan (sandbox)',
    'AURORE-MULTI': u'Cpay Aurore',
    'BANCONTACT': u'Bancontact Mistercash',
    'BILLEASE': u'BillEase',
    'BIZUM': u'Bizum',
    'BIZZBEE_CDX': u'Carte Cadeau Bizzbee',
    'BIZZBEE_CDX_SB': u'Carte Cadeau Bizzbee (sandbox)',
    'BOOST': u'Boost',
    'BOULANGER': u'Carte b+',
    'BOULANGER_SB': u'Carte b+ (sandbox)',
    'BPI': u'BPI',
    'BRICE_CDX': u'Carte Cadeau Brice',
    'BRICE_CDX_SB': u'Carte Cadeau Brice (sandbox)',
    'BUT': u'But',
    'CABAL': u'Cabal',
    'CARNET': u'Carnet',
    'CA_DO_CARTE': u'CA DO Carte',
    'CHQ_DEJ': u'Chèque Déjeuner',
    'COFIDIS_3X_BE': u'Cofidis en 3 fois',
    'COFIDIS_3X_FR': u'Cofidis en 3 fois',
    'COFIDIS_4X_ES': u'Cofidis en 4 vencimientos',
    'COFIDIS_4X_FR': u'Cofidis en 4 fois',
    'COFIDIS_DFPAY_FR': u'Cofidis Pay Later',
    'COFIDIS_LOAN_BE': u'Cofidis en 6-12-18 fois',
    'COFIDIS_LOAN_CB': u'Cofidis en 5-12 fois',
    'COFIDIS_LOAN_ES': u'Cofidis en 6-12-24 vencimientos',
    'COFIDIS_LOAN_FR': u'Amortissable',
    'COFIDIS_LOAN_IT': u'Cofidis Pagodil',
    'COFIDIS_PAY_FR': u'Cofidis Pay', 
    'COM_BARRY_CDX': u'Carte Cadeau Comtesse du Barry',
    'COM_BARRY_CDX_SB': u'Carte Cadeau Comtesse du Barry (sandbox)',
    'CONECS': u'Conecs',
    'CONFORAMA': u'Conforama',
    'CORA': u'Cora',
    'CORA_BLANCHE': u'Cora blanche',
    'CORA_PREM': u'Cora Visa Premier',
    'CORA_VISA': u'Cora Visa',
    'CVCO': u'Chèque-Vacances Connect',
    'DANA': u'Dana',
    'DINERS': u'Diners',
    'DISCOVER': u'Discover',
    'ECCARD': u'EC Card',
    'EDENRED': u'Ticket Restaurant',
    'EDENRED_CC': u'Ticket Cheque Consommation',
    'EDENRED_EC': u'Ticket EcoCheque',
    'EDENRED_SC': u'Ticket Sport & Culture',
    'EDENRED_TC': u'Ticket Compliments',
    'EDENRED_TR': u'Ticket Restaurant',
    'ELO': u'Elo',
    'FLOA_10X': u'Floa en 10 fois',
    'FLOA_3X': u'Floa en 3 fois',
    'FLOA_4X': u'Floa en 4 fois',
    'FLOA_PAYLATER': u'Floa Pay Later',
    'FRANFINANCE_3X': u'Paiement en 3 fois',
    'FRANFINANCE_4X': u'Paiement en 4 fois',
    'FULLCB3X': u'Paiement en 3 fois CB',
    'FULLCB4X': u'Paiement en 4 fois CB',
    'GCASH': u'GCash',
    'GEMO_CDX': u'Carte Cadeau Gémo',
    'GEMO_CDX_SB': u'Carte Cadeau Gémo (sandbox)',
    'GIROPAY': u'Giropay',
    'GOOGLEPAY': u'Google Pay',
    'HIPER': u'Hiper',
    'HIPERCARD': u'Hipercard',
    'IDEAL': u'iDEAL',
    'ILLICADO': u'Carte Illicado',
    'ILLICADO_SB': u'Carte Illicado (sandbox)',
    'IP_WIRE': u'Virement SEPA',
    'IP_WIRE_INST': u'Virement SEPA Instantané',
    'JCB': u'JCB',
    'JOUECLUB_CDX': u'Carte Cadeau Joué Club',
    'JOUECLUB_CDX_SB': u'Carte Cadeau Joué Club (sandbox)',
    'JULES_CDX': u'Carte Cadeau Jules',
    'JULES_CDX_SB': u'Carte Cadeau Jules (sandbox)',
    'KADEOS_CULTURE': u'Carte Kadéos Culture',
    'KADEOS_GIFT': u'Carte Kadéos Zénith',
    'KAKAOPAY': u'Kakao Pay',
    'KREDIVO_ID': u'Krevido',
    'LECLERC': u'Carte Reglo',
    'LEROY-MERLIN': u'Carte Maison Financement',
    'LEROY-MERLIN_SB': u'Carte Maison Financement (sandbox)',
    'MASTERPASS': u'MasterPass',
    'MAYA': u'Maya',
    'MB_WAY': u'MB Way',
    'MC_CORDOBESA': u'Mastercard Cordobesa',
    'MPAY': u'MPay',
    'MULTIBANCO': u'Multibanco',
    'MYBANK': u'MyBank',
    'NARANJA': u'Naranja',
    'NORAUTO': u'Carte Norauto option Financement',
    'NORAUTO_SB': u'Carte Norauto option Financement (sandbox)',
    'ONEY_10X_12X': u'Paiement en 10 ou 12 fois Oney',
    'ONEY_3X_4X': u'Paiement en 3 ou 4 fois Oney',
    'ONEY_ENSEIGNE': u'Cartes enseignes Oney',
    'ONEY_PAYLATER': u'Pay Later Oney',
    'PASS_BEAU_CDX': u'Carte Cadeau Passion Beauté',
    'PASS_BEAU_CDX_SB': u'Carte Cadeau Passion Beauté (sandbox)',
    'PAYCONIQ': u'Payconiq',
    'PAYDIREKT': u'Paydirekt',
    'PAYPAL': u'PayPal',
    'PAYPAL_BNPL': u'PayPal Pay Later',
    'PAYPAL_BNPL_SB': u'PayPal Pay Later Sandbox',
    'PAYPAL_SB': u'PayPal Sandbox',
    'PICWIC': u'Carte Picwic',
    'PICWIC_SB': u'Carte Picwic (sandbox)',
    'POSTFINANCE': u'PostFinance Card',
    'POSTFINANCE_EFIN': u'PostFinance E-Finance',
    'PRESTO': u'Presto',
    'PRZELEWY24': u'Przelewy24',
    'RABBIT_LINE_PAY': u'Rabbit Line Pay',
    'S-MONEY': u'S-money',
    'SAMSUNG_PAY': u'Samsung Pay',
    'SCT': u'Virement SEPA',
    'SDD': u'SEPA direct debit',
    'SODEXO': u'Pass Restaurant',
    'SOFORT_BANKING': u'Sofort',
    'SOROCRED': u'Sorocred',
    'TNG': u'Touch \'n Go eWallet',
    'TOSS': u'Toss',
    'TRUEMONEY': u'TrueMoney Wallet',
    'UPI': u'UPI',
    'VILLAVERDE': u'Carte Cadeau VillaVerde',
    'VILLAVERDE_SB': u'Carte Cadeau VillaVerde (sandbox)',
    'WECHAT': u'WeChat Pay',
}

LYRA_CURRENCIES = [
    ['AUD', '036', 2],
    ['CAD', '124', 2],
    ['CHF', '756', 2],
    ['DKK', '208', 2],
    ['EUR', '978', 2],
    ['GBP', '826', 2],
    ['JPY', '392', 0],
    ['MXN', '484', 2],
    ['NOK', '578', 2],
    ['PLN', '985', 2],
    ['SEK', '752', 2],
    ['USD', '840', 2],
]

LYRA_ONLINE_DOC_URI = {
    'fr': 'https://docs.lyra.com/fr/collect/plugins/',
    'en': 'https://docs.lyra.com/en/collect/plugins/',
    'es': 'https://docs.lyra.com/es-ES/collect/plugins/',
}

LYRA_DOCUMENTATION = {
    'fr': 'Français',
    'en': 'English',
    'es': 'Español',
    'de': 'Deutsch',
    'pt': 'Português',
}

LYRA_PAYMENT_DATA_ENTRY_MODE = {
    'redirect': _lt("Bank data acquisition on payment gateway"),
    'embedded': _lt("Embedded payment fields on merchant site (REST API)"),
    'embedded_extended_with_logos': _lt("Embedded payment fields extended on merchant site with logos (REST API)"),
    'embedded_extended_without_logos': _lt("Embedded payment fields extended on merchant site without logos (REST API)"),
}

LYRA_REST_API_KEYS_DESC = 'REST API keys are available in your Lyra Expert Back Office (menu: Settings > Shops > REST API keys).'